### PR TITLE
propagate user SyntaxError that prevent modules from importing (#1004)

### LINKED ISSUE #1004: Python module syntax errors don't seem to get propagated
If, e.g., you forget a colon in your module definition, SMV doesn't propagate that error or stacktrace back to the Python driver.

### PR DESCRIPTION
**Pull request by laneb**
Fixes #1004. Note that I've reduced the generality of `utils.for_name`, but that generality was not useful to us. In fact, `for_name` is only used in a single place in the code.

### CODE REVIEW

File: src/main/scala/org/tresamigos/smv/DataSetRepo.scala [hunk 1]
```diff
@@ -31,8 +33,10 @@ abstract class DataSetRepoFactory {
 
 class DataSetRepoScala(smvConfig: SmvConfig) extends DataSetRepo {
   val cl = SmvClassLoader(smvConfig, getClass.getClassLoader)
-  def loadDataSet(urn: ModURN): SmvDataSet =
-    (new SmvReflection(cl)).objectNameToInstance[SmvDataSet](urn.fqn)
+  def loadDataSet(urn: ModURN): Option[SmvDataSet] =
+    Try {
+      new SmvReflection(cl).objectNameToInstance[SmvDataSet](urn.fqn)
```
Comment (AliTajeldin) [inline src/main/scala/org/tresamigos/smv/DataSetRepo.scala]: wouldn't this "eat up" any exceptions while loading the scala modules?  Or is the only possible exception on the scala side is if the module was not there?

**Comment by laneb** [comment]
There is no risk (as far as I'm aware) of a runtime error in client code
causing an error during reflection. Syntax errors, undefined names, and
missing imports, which cause the bulk of errors during reflection on the
Python side, will prevent Scala code from compiling in the first place.
Correct me if I'm wrong, but I don't think any code will be executed as a
consequence of reflection in Scala (vs Python, where imports are executed
like a script on the first import). I suppose it is possible that there are
more esoteric errors that could occur during reflection, and I can look
into that if you want, but this approach for Scala code has been pretty
stable and precedes the DataSetManager.

**Comment by AliTajeldin** [comment]
@laneb got it.  Even if there are some esoteric cases, we are not really using the scala interface that much anyway.
