### PR TITLE
I1098 add validation results to metadata

### LINKED ISSUE #1098: Need a way to compare current validation results to historical ones
User wants to verify that, e.g., the number of failed records in this run does exceed the average for this dataset by more than some threshold proportion. For access to historical validation results, the obvious approach is to add the results to the default metadata and take advantage of the metadata history. We could also create a validation history in parallel to the metadata history, but it makes more sense to me to treat the validation result as another piece of metadata. If validation results are added to the metadata, we could just let the user compare results in `validateMetadata`. For a more tailored API we could also create a method to compare _just_ the validation results, but that could come later if needed.

### PR DESCRIPTION
**Pull request by laneb**
Resolves #1098.

### CODE REVIEW

File: src/main/scala/org/tresamigos/smv/SmvDataSet.scala [hunk 1]
```diff
@@ -580,7 +586,7 @@ abstract class SmvDataSet extends FilenamePart {
     //Same as in persist, publish null string as a special value with assumption that it's not
     //a valid data value
     handler.saveAsCsvWithSchema(df, strNullValue = "_SmvStrNull_")
-    getOrCreateMetadata(Some(df)).saveToFile(app.sc, publishMetaPath(version))
+    getMetadata.saveToFile(app.sc, publishMetaPath(version))
```
Comment (cloudysail) [inline src/main/scala/org/tresamigos/smv/SmvDataSet.scala]: Not sure if I missed anything. We used to pass `Some(df)` but now we call `getMetadata` in which we call `getOrCreateMetadata(None, None)`?

File: src/main/python/smv/runinfo.py [hunk 2]
```diff
@@ -110,18 +110,38 @@ def metadata_history(self, ds_name):
...
         else:
             fqns = [self.jcollector.inferFqn(ds_name)]
         msg = 'datasets: %s' % fqns
+
+        def items_to_report(fqn):
+            validation = self.dqm_validation(fqn)
+            metadata = self.metadata(fqn)
+            # Remove validation results from metadata (if they exist) as we are reporting it above
+            try:
+                del metadata['_validation']
```
Comment (cloudysail) [inline src/main/python/smv/runinfo.py]: If we just do not add `("dqm validation", validation)` to items, but use `metadata['_validation']` to show the `DqmValiationResult`.  Would this work?

File: src/main/scala/org/tresamigos/smv/SmvDataSet.scala [hunk 3]
```diff
@@ -464,6 +467,9 @@ abstract class SmvDataSet extends FilenamePart {
     resMetadata.addDependencyMetadata(resolvedRequiresDS)
     dfOpt foreach {resMetadata.addSchemaMetadata}
     timestamp foreach {resMetadata.addTimestamp}
+    // note that validation result will be *excluded* from metadata provided to
```
Comment (AliTajeldin) [inline src/main/scala/org/tresamigos/smv/SmvDataSet.scala]: Not sure I understand what this comment was intending to say.  Which validation result and when is the metadata validated?

File: src/main/scala/org/tresamigos/smv/SmvDataSet.scala (hunk 1 above)
Comment (laneb) [reply src/main/scala/org/tresamigos/smv/SmvDataSet.scala]: The metadata has already been generated and saved to file by the time we publish, so `readPersistedMetadata` will return `Some` and we will not call `getOrCreateMetadata(None, None)`. This is very similar to the `getMetadataHistory` on the line below.  I reread this code a couple of times, and I don't this it's necessary to regenerate the metadata here. And in all likelihood, the user metadata will not be cached here because we didn't persist this output within this same transaction, so regenerating the metadata could be costly.

File: src/main/python/smv/runinfo.py (hunk 2 above)
Comment (laneb) [reply src/main/python/smv/runinfo.py]: It would deduplicate the validation results in the report, but it would also make the report less readable. And the metadata is not the source of truth on validation, because when validation fails there will be validation results in `*.valid` but no metadata.

File: src/main/scala/org/tresamigos/smv/SmvDataSet.scala (hunk 1 above)
Comment (laneb) [reply src/main/scala/org/tresamigos/smv/SmvDataSet.scala]: I'll add a comment to clarify that for both the metadata and metadata history.

File: src/main/scala/org/tresamigos/smv/SmvMetaData.scala [hunk 4]
```diff
@@ -55,6 +57,19 @@ class SmvMetadata(val builder: MetadataBuilder = new MetadataBuilder) {
     builder.putString("_timestamp", dt.toString)
   }
 
+  /**
+   * Add validation result (including DQM state) to metadata
+   */
+   def addValidationResult(result: DqmValidationResult) = {
```
[the remark this answers is not in the document]
Comment (laneb) [reply src/main/scala/org/tresamigos/smv/SmvMetaData.scala]: Sure.

File: src/main/scala/org/tresamigos/smv/SmvDataSet.scala (hunk 3 above)
Comment (laneb) [reply src/main/scala/org/tresamigos/smv/SmvDataSet.scala]: `getOrCreateMetadata` is called to get metadata for metadata validation, and to get metadata to persist. At time of metadata validation, there is no DQM validation result to include in the metadata, as the validation hasn't completed. At the time the metadata is persisted, DQM validation has completed, so we have a result to include. We now have 3 possible degrees of 'completeness' for metadata: default metadata only _without_ validation result, user metadata + default metadata _without_ validation result, and user metadata + default metadata _with_ validation result. I'll put some clearer and better placed comments to explain this.
